# -*- coding: utf-8 -*-
# Deployment settings for game.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/6.3.3BETA/s3e/makefile_builder/mkb.py', 'c:/Users/Bilal/Repositories/GameJam2/game.mkb', '--deploy-only']
mkb = 'c:/Users/Bilal/Repositories/GameJam2/game.mkb'
mkf = [u'c:\\users\\bilal\\appdata\\roaming\\marmalade\\packages\\6.3.3\\sqlite_3.6.10\\sqlite.mkf', 'c:\\marmalade\\6.3.3beta\\modules\\iw2d\\iw2d.mkf', 'c:\\marmalade\\6.3.3beta\\modules\\iwgx\\iwgx.mkf', 'c:\\marmalade\\6.3.3beta\\modules\\iwgeom\\iwgeom.mkf', 'c:\\marmalade\\6.3.3beta\\modules\\iwutil\\iwutil.mkf', 'c:\\marmalade\\6.3.3beta\\modules\\third_party\\libjpeg\\libjpeg.mkf', 'c:\\marmalade\\6.3.3beta\\modules\\third_party\\libpng\\libpng.mkf', 'c:\\marmalade\\6.3.3beta\\modules\\third_party\\zlib\\zlib.mkf', 'c:\\marmalade\\6.3.3beta\\modules\\iwresmanager\\iwresmanager.mkf', 'c:\\marmalade\\6.3.3beta\\modules\\iwgl\\iwgl.mkf', 'c:\\marmalade\\6.3.3beta\\modules\\iwgxfont\\iwgxfont.mkf', 'c:\\marmalade\\6.3.3beta\\modules\\third_party\\tiniconv\\tiniconv.mkf', 'c:\\marmalade\\6.3.3beta\\examples\\soundengine\\soundengine.mkf', 'c:\\marmalade\\6.3.3beta\\extensions\\messagebox\\messagebox.mkf', 'c:\\users\\bilal\\repositories\\gamejam2\\spine.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/Bilal/Repositories/GameJam2/data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'game'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'game'
    long_caption = 'game'
    version = [1, 0, 0]
    config = ['c:/Users/Bilal/Repositories/GameJam2/data/app.icf']
    data_dir = 'c:/Users/Bilal/Repositories/GameJam2/data'
    iphone_link_lib = []
    wp8_ext_managed_dll = []
    linux_ext_lib = []
    android_extra_application_manifest = []
    iphone_link_libdir = []
    iphone_link_libdirs = ['c:/marmalade/6.3.3beta/extensions/messagebox/lib/iphone']
    iphone_link_opts = ['-weak_framework CoreText -weak_framework UIKit -weak_framework Security -weak_framework AddressBook -weak_framework AddressBookUI -weak_framework MapKit -lsqlite3.0']
    android_external_jars = ['c:/marmalade/6.3.3beta/extensions/messagebox/lib/android/MessageBox.jar']
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    wp8_ext_native_dll = []
    win32_ext_dll = ['c:/marmalade/6.3.3beta/extensions/messagebox/lib/win32/MessageBox.dll']
    android_so = ['c:/marmalade/6.3.3beta/extensions/messagebox/lib/android/libMessageBox.so']
    osx_ext_dll = ['c:/marmalade/6.3.3beta/extensions/messagebox/lib/osx/libMessageBox.dylib']
    wp8_ext_capabilities = []
    iphone_link_libs = ['MessageBox']
    target = {
         'gcc_x86' : {
                   'debug'   : r'c:/Users/Bilal/Repositories/GameJam2/build_game_vc11/Debug_game_VC11_gcc_x86/game.so',
                   'release' : r'c:/Users/Bilal/Repositories/GameJam2/build_game_vc11/Release_game_VC11_gcc_x86/game.so',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:/Users/Bilal/Repositories/GameJam2/build_game_vc11/Debug_game_VC11_gcc_mips/game.so',
                   'release' : r'c:/Users/Bilal/Repositories/GameJam2/build_game_vc11/Release_game_VC11_gcc_mips/game.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:/Users/Bilal/Repositories/GameJam2/build_game_vc11/Debug_game_VC11_gcc_arm/game.s3e',
                   'release' : r'c:/Users/Bilal/Repositories/GameJam2/build_game_vc11/Release_game_VC11_gcc_arm/game.s3e',
                 },
         'mips' : {
                   'debug'   : r'c:/Users/Bilal/Repositories/GameJam2/build_game_vc11/Debug_game_VC11_gcc_mips/game.so',
                   'release' : r'c:/Users/Bilal/Repositories/GameJam2/build_game_vc11/Release_game_VC11_gcc_mips/game.so',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'c:/Users/Bilal/Repositories/GameJam2/build_game_vc11/Debug_game_VC11_gcc_x86_android/game.so',
                   'release' : r'c:/Users/Bilal/Repositories/GameJam2/build_game_vc11/Release_game_VC11_gcc_x86_android/game.so',
                 },
         'arm' : {
                   'debug'   : r'c:/Users/Bilal/Repositories/GameJam2/build_game_vc11/Debug_game_VC11_arm/game.s3e',
                   'release' : r'c:/Users/Bilal/Repositories/GameJam2/build_game_vc11/Release_game_VC11_arm/game.s3e',
                 },
         'x86' : {
                   'debug'   : r'c:/Users/Bilal/Repositories/GameJam2/build_game_vc11/Debug_game_VC11_x86/game.s86',
                   'release' : r'c:/Users/Bilal/Repositories/GameJam2/build_game_vc11/Release_game_VC11_x86/game.s86',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()
